### ISSUE TITLE
Update elements where user action is required

### ISSUE THREAD

**Issue by trevordmiller** [rebornix/vscode-nova#6]
- [ ] User action elements should use nova-colors with better contrast (either use foreground color of `uiGroups.userActionNeeded` with normal `uiGroups.background` as shown in the vim examples below, or use foreground color of `uiGroups.backgroundShade` with the `uiGroups.userActionNeeded` background that is currently implemented)

### Current
![image](https://user-images.githubusercontent.com/5497885/30573166-730b67e4-9caf-11e7-9ada-866943c92457.png)

### Expected (examples from nova-vim):

![image](https://user-images.githubusercontent.com/5497885/30573227-c7ca7680-9caf-11e7-8df0-6544051ca220.png)

![image](https://user-images.githubusercontent.com/5497885/30573229-d060945a-9caf-11e7-8a36-bdd951cb7011.png)

**Comment by rebornix** [comment]
VSCode renders source code and decorations in different layers, in above case, the red/green backgrounds are decorations while the text are rendered based on TextMate theme. So basically right now there is no way to customize the text color in selected ranges. A workaround here is using background color with some transparency. 

![image](https://user-images.githubusercontent.com/876920/30575299-b218c558-9cb4-11e7-8076-181e211c4591.png)

In this way, the added text or deleted text still has the colors defined by TextMate Grammar.

**Comment by trevordmiller** [comment]
Gotcha. As long as the contrast can be improved because the grey on red is hard to read.

**Comment by trevordmiller** [comment]
Ok no problem, I'll close this :)
