### ISSUE TITLE
Update elements that aren't using nova colors

### ISSUE THREAD

**Issue by trevordmiller** [rebornix/vscode-nova#7]
- [ ] Update elements that are using colors not in `nova-colors`

A few examples:

![image](https://user-images.githubusercontent.com/5497885/30573453-3c27e70a-9cb1-11e7-8e02-616b7e29a4d5.png)

Examples like the highlighted letters in this screenshot ^ should be using [`uiGroups.userCurrentGroup` from nova-colors](https://github.com/trevordmiller/nova-colors/blob/master/src/index.js#L25-L73) as that is the color meaning associated with the user's state (like making a search)

A few more examples:

![image](https://user-images.githubusercontent.com/5497885/30573029-b71f8e66-9cae-11e7-8eff-fe52befb3878.png)

![image](https://user-images.githubusercontent.com/5497885/30573280-2ccdfd86-9cb0-11e7-86cd-8332ece080bf.png)

![image](https://user-images.githubusercontent.com/5497885/30573290-3b0ed172-9cb0-11e7-8dff-0bbe879c30e7.png)

![image](https://user-images.githubusercontent.com/5497885/30573298-44dd8e64-9cb0-11e7-826d-24436546a465.png)

![image](https://user-images.githubusercontent.com/5497885/30573489-6dc11bba-9cb1-11e7-8568-6a4249cfacad.png)

![image](https://user-images.githubusercontent.com/5497885/30573309-56045bc8-9cb0-11e7-99d0-6024de532323.png)

![image](https://user-images.githubusercontent.com/5497885/30573576-e96a813e-9cb1-11e7-80fd-0ca7ba256be9.png)

![image](https://user-images.githubusercontent.com/5497885/30573596-09b83c06-9cb2-11e7-96da-811b25e119d9.png)

etc.

These are just a few examples I saw with a quick look around, but any place that is using colors outside of nova-colors and/or have incorrect color meanings being used should be updated to use nova-colors fully: https://github.com/trevordmiller/nova-colors/blob/master/src/index.js#L25-L73

**Comment by rebornix** [comment]
Quick Pick
![image](https://user-images.githubusercontent.com/876920/30616786-43e57fd8-9d48-11e7-93d8-ebd25ab2cf9e.png)

Search highlight
![image](https://user-images.githubusercontent.com/876920/30617073-5b9193d2-9d49-11e7-8571-ff013dcf2cc4.png)

Gutter/Overview ruler
![image](https://user-images.githubusercontent.com/876920/30617323-58ff4faa-9d4a-11e7-87f0-dcdec18d5aa2.png)

**Comment by rebornix** [comment]
I added nova colors to elements which are customizable at this moment as above. Others like breakpoint, find widget options color, git buttons, we don't have a chance to tweak them now.

The file icons are pretty interesting though, we don't allow you to customize them in color theme but extensions can provide a icon theme together with color theme, for example, Monokai Pro ships a set of icon themes together with its color theme https://github.com/Monokai/monokai-pro-vscode/blob/master/img/monokai-pro.png .

**Comment by trevordmiller** [comment]
@rebornix Sounds good. The only thing I would still request you still change before closing this issue is using the version control nova-colors for the git gutter; see https://github.com/trevordmiller/nova-colors/blob/master/src/index.js#L45-L50.

Here is an example of this from nova-vim: https://github.com/trevordmiller/nova-vim/blob/master/src/index.js#L87-L95
