### ISSUE TITLE
Update elements with poor contrast

### ISSUE THREAD

**Issue by trevordmiller** [rebornix/vscode-nova#8]
- [ ] Update elements with poor contrast

### Current

A few examples of poor contrast:

![image](https://user-images.githubusercontent.com/5497885/30573444-28913a20-9cb1-11e7-89d5-5b016d0e57ce.png)

![image](https://user-images.githubusercontent.com/5497885/30573475-5f1fd4de-9cb1-11e7-8f2d-5b209b563271.png)

![image](https://user-images.githubusercontent.com/5497885/30573518-9258b21c-9cb1-11e7-8e68-0d16b216b7d9.png)

etc.

### Expected (examples from nova-vim):

Examples with good contrast:

![image](https://user-images.githubusercontent.com/5497885/30573390-d4b00486-9cb0-11e7-8372-cfe81c8a216c.png)

![image](https://user-images.githubusercontent.com/5497885/30573394-dd22f704-9cb0-11e7-9b6b-ecd31c408357.png)

![image](https://user-images.githubusercontent.com/5497885/30573419-099fb164-9cb1-11e7-8632-a872732ec299.png)

**Comment by rebornix** [comment]
It shares the same reason with https://github.com/rebornix/vscode-nova/issues/6#issuecomment-330423015 , Code doesn't allow us to change the color of text under selection or matched text, Code recommends to use background color.

**Comment by trevordmiller** [comment]
Ok no problem, I'll close this :)
